with-expecter: True
inpackage: True
dir: mocks/
mockname: "{{.InterfaceName}}"
outpkg: "{{.PackageName}}"
filename: "{{.InterfaceName}}.go"
all: True
packages:
  github.com/rshelekhov/reframed/internal/storage:
    config:
      recursive: True