env: "local" # local, development, production

http_server:
  address: "localhost:8082"
  timeout: 4s
  idle_timeout: 60s
postgres:
  db_name: "remedi_dev"
  host: "localhost"
  port: "5432"
  user: "app"
  password: "p@ssw0rd"
  sslmode: "disable"